#Splash screen properties
#Tue Oct 06 13:15:36 SAMT 2026
background=0x1A1208
bar=0x4A9C3F
barBackground=0x1F2A18
barBorder=0x2F6B28
enabled=false
font=0xF0E6C8
fontTexture=textures/font/ascii.png
forgeTexture=fml\:textures/gui/forge.gif
logoOffset=0
logoTexture=textures/gui/title/mojang.png
resourcePackPath=resources
rotate=false
