#LOTR+ portable JRE marker
#Sun Sep 20 22:44:34 SAMT 2026
version=21
javaw=C\:\\Users\\James\\AppData\\Roaming\\PrismLauncher\\instances\\Middle-Earth Chronicles- New Chapter\\minecraft\\config\\lotr\\runtime\\jdk-21\\jdk-21.0.12.1+1-jre\\bin\\javaw.exe
vendor=eclipse-temurin
