#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Dec 21 11:50:37 SAMT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=BSL_v8.4.zip
